/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ameer
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddProd
     */
    public AddAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLheader = new javax.swing.JLabel();
        jLheader1 = new javax.swing.JLabel();
        jLheader2 = new javax.swing.JLabel();
        jLheader3 = new javax.swing.JLabel();
        jLheader4 = new javax.swing.JLabel();
        jLheader5 = new javax.swing.JLabel();
        jTsearchbyname3 = new javax.swing.JTextField();
        jTsearchbyname4 = new javax.swing.JTextField();
        jTsearchbyname5 = new javax.swing.JTextField();
        jBsearchaddprod = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLheader6 = new javax.swing.JLabel();
        jTsearchbyname7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jLheader.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader.setText("ADD ADMIN");

        jLheader1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader1.setText("ID :");

        jLheader2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader2.setText("User Name :");

        jLheader3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader3.setText("Gender :");

        jLheader4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader4.setText("Birth Date :");

        jLheader5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader5.setText("Address :");

        jTsearchbyname3.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname3.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname3.setText(" ");
        jTsearchbyname3.setBorder(null);
        jTsearchbyname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname3ActionPerformed(evt);
            }
        });

        jTsearchbyname4.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname4.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname4.setText(" ");
        jTsearchbyname4.setBorder(null);
        jTsearchbyname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname4ActionPerformed(evt);
            }
        });

        jTsearchbyname5.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname5.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname5.setBorder(null);
        jTsearchbyname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname5ActionPerformed(evt);
            }
        });

        jBsearchaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod.setText("ADD");
        jBsearchaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprodMousePressed(evt);
            }
        });
        jBsearchaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprodActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(45, 72, 77));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel1.setBackground(new java.awt.Color(241, 223, 169));
        jLabel1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        jLheader6.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader6.setText("Add Password :");

        jTsearchbyname7.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname7.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname7.setBorder(null);
        jTsearchbyname7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname7ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(241, 223, 169));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jRadioButton1.setText("Male");

        jRadioButton2.setBackground(new java.awt.Color(241, 223, 169));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLheader))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLheader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLheader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLheader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLheader5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLheader6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))
                            .addComponent(jTsearchbyname5)
                            .addComponent(jTsearchbyname3)
                            .addComponent(jTsearchbyname4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTsearchbyname7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jBsearchaddprod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLheader)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLheader1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(jLheader3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLheader4)
                        .addGap(36, 36, 36)
                        .addComponent(jLheader5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTsearchbyname4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jTsearchbyname5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jTsearchbyname3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheader6)
                    .addComponent(jTsearchbyname7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsearchaddprod)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTsearchbyname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname3ActionPerformed

    private void jTsearchbyname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname4ActionPerformed

    private void jTsearchbyname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname5ActionPerformed

    private void jBsearchaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprodActionPerformed

    private void jBsearchaddprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprodMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");   
            
                        String strStmt="insert into admininfo (ID, USERNAME, GENDER,BIRTH_DATE,ADDRESS,PASSWORD) values (?,?,?,to_date(?, 'dd-MM-yyyy'),?,?)";
                        PreparedStatement pst= conn.prepareStatement(strStmt);
                        if(jTsearchbyname4.getText().trim().isEmpty() || jTsearchbyname5.getText().trim().isEmpty() || (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) || jTsearchbyname3.getText().trim().isEmpty()||jDateChooser1.getDate()==null){
                        jLabel1.setText("Please enter the empty field");
                        }
                        else{
                        pst.setInt(1, Integer.parseInt(jTsearchbyname4.getText().trim()));
            
                        pst.setString(2, jTsearchbyname5.getText());
                        if(jRadioButton1.isSelected()){
                            pst.setString(3, "male");
                        }else{
                            pst.setString(3, "female");
                        }         
                        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                        String date= sdf.format(jDateChooser1.getDate());
                        pst.setString(4, date);
            
                        pst.setString(5,jTsearchbyname3.getText());
                        pst.setString(6,jTsearchbyname7.getText());
                        pst.executeUpdate();
                        jLabel1.setText("The ADMIN Is Added");
                        }
                        conn.setAutoCommit(false);
                        conn.commit();
                        conn.close();
                        
                  
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jBsearchaddprodMousePressed

    private void jTsearchbyname7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBsearchaddprod;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLheader;
    private javax.swing.JLabel jLheader1;
    private javax.swing.JLabel jLheader2;
    private javax.swing.JLabel jLheader3;
    private javax.swing.JLabel jLheader4;
    private javax.swing.JLabel jLheader5;
    private javax.swing.JLabel jLheader6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTsearchbyname3;
    private javax.swing.JTextField jTsearchbyname4;
    private javax.swing.JTextField jTsearchbyname5;
    private javax.swing.JTextField jTsearchbyname7;
    // End of variables declaration//GEN-END:variables
}
