/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;


import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Statement;
import javax.swing.JPanel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ameer
 */
public class AdminInterface extends javax.swing.JFrame {

    /**
     * Creates new form AdminInterface
     */
    public AdminInterface() {
        initComponents();
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs;
        LinkedList inls = new LinkedList<String>();
        
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");  
            String strStmt="select CAR_TYPE from CAR";
            PreparedStatement pst= conn.prepareStatement(strStmt);
            rs = pst.executeQuery();

            jCcartype.addItem("ALL");
                
                while(rs.next()){
                    String ins =rs.getString(1);
                    if(!inls.contains(ins)){
                        jCcartype.addItem(ins);
                        inls.add(ins);
                    }
                    
                }
            conn.close();
            jCcarname.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(AddProd.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGPmain = new com.k33ptoo.components.KGradientPanel();
        kGPside = new com.k33ptoo.components.KGradientPanel();
        jPsell = new javax.swing.JPanel();
        jLiconsell = new javax.swing.JLabel();
        jLsell = new javax.swing.JLabel();
        jPlogout = new javax.swing.JPanel();
        jLlogout = new javax.swing.JLabel();
        jPbenefits = new javax.swing.JPanel();
        jLiconbenefits = new javax.swing.JLabel();
        jLbenefits = new javax.swing.JLabel();
        jPaddproduct = new javax.swing.JPanel();
        jLiconaddpro = new javax.swing.JLabel();
        jLaddpro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPorder = new javax.swing.JPanel();
        jLiconorder = new javax.swing.JLabel();
        jLorder = new javax.swing.JLabel();
        jPadmininfo = new javax.swing.JPanel();
        jLadmininfo = new javax.swing.JLabel();
        jLadminninfo = new javax.swing.JLabel();
        kGPright = new com.k33ptoo.components.KGradientPanel();
        jLexit = new javax.swing.JLabel();
        jLexittt = new javax.swing.JLabel();
        jLheader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPsellpnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTSELL = new javax.swing.JTable();
        jCcartype = new javax.swing.JComboBox<>();
        jCcarname = new javax.swing.JComboBox<>();
        jBsearchsell = new javax.swing.JButton();
        jLcartype = new javax.swing.JLabel();
        jLcarname = new javax.swing.JLabel();
        jBprintbill = new javax.swing.JButton();
        jBdeletS = new javax.swing.JButton();
        jPaddpnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaddprod = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jTsearchbyname = new javax.swing.JTextField();
        jBaddprod = new javax.swing.JButton();
        jBsearchsell3 = new javax.swing.JButton();
        jBsearchsell4 = new javax.swing.JButton();
        jPadmininfoo = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTadmininfo = new javax.swing.JTable();
        jBchangepass = new javax.swing.JButton();
        jBchangeadmininfo = new javax.swing.JButton();
        jBchangepass1 = new javax.swing.JButton();
        jBchangepass2 = new javax.swing.JButton();
        jPstatistics = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPordercard = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTorder = new javax.swing.JTable();
        jTsearchbycustname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jBsearchorder1 = new javax.swing.JButton();
        jBsearchorder2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        kGPmain.setBackground(new java.awt.Color(255, 255, 255));
        kGPmain.setkEndColor(new java.awt.Color(255, 255, 255));
        kGPmain.setkGradientFocus(50);
        kGPmain.setkStartColor(new java.awt.Color(255, 255, 255));
        kGPmain.setPreferredSize(new java.awt.Dimension(1000, 600));
        kGPmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGPside.setkEndColor(new java.awt.Color(241, 223, 169));
        kGPside.setkGradientFocus(50);
        kGPside.setkStartColor(new java.awt.Color(241, 223, 169));
        kGPside.setPreferredSize(new java.awt.Dimension(300, 600));
        kGPside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPsell.setBackground(new java.awt.Color(234, 199, 94));
        jPsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPsellMousePressed(evt);
            }
        });

        jLiconsell.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\shopping-cart-add.png")); // NOI18N

        jLsell.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLsell.setForeground(new java.awt.Color(255, 255, 255));
        jLsell.setText("SELL PRODUCT");

        javax.swing.GroupLayout jPsellLayout = new javax.swing.GroupLayout(jPsell);
        jPsell.setLayout(jPsellLayout);
        jPsellLayout.setHorizontalGroup(
            jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLiconsell, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLsell)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPsellLayout.setVerticalGroup(
            jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPsellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLiconsell, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLsell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGPside.add(jPsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 60));

        jPlogout.setBackground(new java.awt.Color(234, 199, 94));
        jPlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPlogoutMousePressed(evt);
            }
        });
        jPlogout.setLayout(new java.awt.GridBagLayout());

        jLlogout.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLlogout.setForeground(new java.awt.Color(255, 255, 255));
        jLlogout.setText("LOGOUT");
        jPlogout.add(jLlogout, new java.awt.GridBagConstraints());

        kGPside.add(jPlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 220, 60));

        jPbenefits.setBackground(new java.awt.Color(234, 199, 94));
        jPbenefits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPbenefitsMousePressed(evt);
            }
        });

        jLiconbenefits.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\statistics.png")); // NOI18N

        jLbenefits.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLbenefits.setForeground(new java.awt.Color(255, 255, 255));
        jLbenefits.setText("STATISTICS");

        javax.swing.GroupLayout jPbenefitsLayout = new javax.swing.GroupLayout(jPbenefits);
        jPbenefits.setLayout(jPbenefitsLayout);
        jPbenefitsLayout.setHorizontalGroup(
            jPbenefitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbenefitsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLiconbenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbenefits)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPbenefitsLayout.setVerticalGroup(
            jPbenefitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbenefitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPbenefitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLiconbenefits, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLbenefits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGPside.add(jPbenefits, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 220, 60));

        jPaddproduct.setBackground(new java.awt.Color(234, 199, 94));
        jPaddproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPaddproductMousePressed(evt);
            }
        });

        jLiconaddpro.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\plus (1).png")); // NOI18N

        jLaddpro.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLaddpro.setForeground(new java.awt.Color(255, 255, 255));
        jLaddpro.setText("ADD PRODUCT");

        javax.swing.GroupLayout jPaddproductLayout = new javax.swing.GroupLayout(jPaddproduct);
        jPaddproduct.setLayout(jPaddproductLayout);
        jPaddproductLayout.setHorizontalGroup(
            jPaddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaddproductLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLiconaddpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLaddpro)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPaddproductLayout.setVerticalGroup(
            jPaddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaddproductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaddproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLiconaddpro, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLaddpro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGPside.add(jPaddproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\Caggyttytytpture.PNG")); // NOI18N
        kGPside.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 270, 180));

        jPorder.setBackground(new java.awt.Color(234, 199, 94));
        jPorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPorderMousePressed(evt);
            }
        });

        jLiconorder.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\clipboard.png")); // NOI18N

        jLorder.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLorder.setForeground(new java.awt.Color(255, 255, 255));
        jLorder.setText("ORDER");

        javax.swing.GroupLayout jPorderLayout = new javax.swing.GroupLayout(jPorder);
        jPorder.setLayout(jPorderLayout);
        jPorderLayout.setHorizontalGroup(
            jPorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPorderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLiconorder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLorder)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPorderLayout.setVerticalGroup(
            jPorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLiconorder, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGPside.add(jPorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 60));

        jPadmininfo.setBackground(new java.awt.Color(234, 199, 94));
        jPadmininfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPadmininfoMousePressed(evt);
            }
        });

        jLadmininfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\info.png")); // NOI18N

        jLadminninfo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLadminninfo.setForeground(new java.awt.Color(255, 255, 255));
        jLadminninfo.setText("ADMIN INFO");

        javax.swing.GroupLayout jPadmininfoLayout = new javax.swing.GroupLayout(jPadmininfo);
        jPadmininfo.setLayout(jPadmininfoLayout);
        jPadmininfoLayout.setHorizontalGroup(
            jPadmininfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPadmininfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLadmininfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLadminninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPadmininfoLayout.setVerticalGroup(
            jPadmininfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPadmininfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPadmininfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLadmininfo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLadminninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        kGPside.add(jPadmininfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 60));

        kGPmain.add(kGPside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 220, 610));

        kGPright.setkEndColor(new java.awt.Color(241, 223, 169));
        kGPright.setkStartColor(new java.awt.Color(241, 223, 169));

        jLexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\cross (1).png")); // NOI18N
        jLexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLexitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLexitMousePressed(evt);
            }
        });

        jLexittt.setFont(new java.awt.Font("Garamond", 0, 12)); // NOI18N

        jLheader.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader.setText("GT CAR");

        javax.swing.GroupLayout kGPrightLayout = new javax.swing.GroupLayout(kGPright);
        kGPright.setLayout(kGPrightLayout);
        kGPrightLayout.setHorizontalGroup(
            kGPrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGPrightLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLheader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 599, Short.MAX_VALUE)
                .addComponent(jLexittt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLexit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        kGPrightLayout.setVerticalGroup(
            kGPrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPrightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGPrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLheader)
                    .addComponent(jLexit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLexittt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        kGPmain.add(kGPright, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 820, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPsellpnl.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        jTSELL.setAutoCreateRowSorter(true);
        jTSELL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTSELL.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTSELL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial ID", "Product Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTSELL.setGridColor(new java.awt.Color(255, 255, 255));
        jTSELL.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane1.setViewportView(jTSELL);
        if (jTSELL.getColumnModel().getColumnCount() > 0) {
            jTSELL.getColumnModel().getColumn(0).setResizable(false);
            jTSELL.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTSELL.getColumnModel().getColumn(1).setResizable(false);
            jTSELL.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTSELL.getColumnModel().getColumn(2).setResizable(false);
            jTSELL.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTSELL.getColumnModel().getColumn(3).setResizable(false);
            jTSELL.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jCcartype.setEditable(true);
        jCcartype.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jCcartype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcartypeActionPerformed(evt);
            }
        });

        jCcarname.setEditable(true);
        jCcarname.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jCcarname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcarnameActionPerformed(evt);
            }
        });

        jBsearchsell.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchsell.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchsell.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchsell.setText("Search");
        jBsearchsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchsellMousePressed(evt);
            }
        });
        jBsearchsell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchsellActionPerformed(evt);
            }
        });

        jLcartype.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLcartype.setText("Car Type:");

        jLcarname.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLcarname.setText("Car Name:");

        jBprintbill.setBackground(new java.awt.Color(241, 223, 169));
        jBprintbill.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBprintbill.setForeground(new java.awt.Color(51, 51, 51));
        jBprintbill.setText("Print Bill");
        jBprintbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBprintbillMousePressed(evt);
            }
        });
        jBprintbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprintbillActionPerformed(evt);
            }
        });

        jBdeletS.setBackground(new java.awt.Color(241, 223, 169));
        jBdeletS.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBdeletS.setForeground(new java.awt.Color(51, 51, 51));
        jBdeletS.setText("DELETE PRODUCT");
        jBdeletS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBdeletSMousePressed(evt);
            }
        });
        jBdeletS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPsellpnlLayout = new javax.swing.GroupLayout(jPsellpnl);
        jPsellpnl.setLayout(jPsellpnlLayout);
        jPsellpnlLayout.setHorizontalGroup(
            jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellpnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsellpnlLayout.createSequentialGroup()
                        .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPsellpnlLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jCcartype, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCcarname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jBsearchsell, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPsellpnlLayout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPsellpnlLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jBdeletS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBprintbill, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))))
                        .addGap(39, 39, 39))
                    .addGroup(jPsellpnlLayout.createSequentialGroup()
                        .addComponent(jLcartype, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLcarname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPsellpnlLayout.setVerticalGroup(
            jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsellpnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcartype)
                    .addComponent(jLcarname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCcartype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCcarname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsearchsell))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPsellpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBprintbill)
                    .addComponent(jBdeletS))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPsellpnl, "card2");

        jPaddpnl.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        jTaddprod.setAutoCreateRowSorter(true);
        jTaddprod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTaddprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial ID", "Product Name", "Quantity", "Date Of Purchase", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTaddprod.setGridColor(new java.awt.Color(255, 255, 255));
        jTaddprod.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane2.setViewportView(jTaddprod);
        if (jTaddprod.getColumnModel().getColumnCount() > 0) {
            jTaddprod.getColumnModel().getColumn(0).setResizable(false);
            jTaddprod.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTaddprod.getColumnModel().getColumn(1).setResizable(false);
            jTaddprod.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTaddprod.getColumnModel().getColumn(2).setResizable(false);
            jTaddprod.getColumnModel().getColumn(2).setPreferredWidth(5);
            jTaddprod.getColumnModel().getColumn(3).setResizable(false);
            jTaddprod.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTaddprod.getColumnModel().getColumn(4).setResizable(false);
            jTaddprod.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jTsearchbyname.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jTsearchbyname.setText("SEARCH BY NAME");
        jTsearchbyname.setBorder(null);
        jTsearchbyname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchbynameMousePressed(evt);
            }
        });
        jTsearchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbynameActionPerformed(evt);
            }
        });
        jTsearchbyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTsearchbynameKeyReleased(evt);
            }
        });

        jBaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBaddprod.setText("ADD PRODUCT");
        jBaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBaddprodMousePressed(evt);
            }
        });
        jBaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddprodActionPerformed(evt);
            }
        });

        jBsearchsell3.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchsell3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchsell3.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchsell3.setText("DELETE PRODUCT");
        jBsearchsell3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchsell3MousePressed(evt);
            }
        });
        jBsearchsell3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchsell3ActionPerformed(evt);
            }
        });

        jBsearchsell4.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchsell4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchsell4.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchsell4.setText("EDIT PRODUCT");
        jBsearchsell4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchsell4MousePressed(evt);
            }
        });
        jBsearchsell4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchsell4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaddpnlLayout = new javax.swing.GroupLayout(jPaddpnl);
        jPaddpnl.setLayout(jPaddpnlLayout);
        jPaddpnlLayout.setHorizontalGroup(
            jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaddpnlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jBsearchsell3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsearchsell4)
                .addGap(54, 54, 54))
            .addGroup(jPaddpnlLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaddpnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPaddpnlLayout.createSequentialGroup()
                        .addGroup(jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTsearchbyname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBaddprod)
                        .addGap(56, 56, 56))))
        );
        jPaddpnlLayout.setVerticalGroup(
            jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaddpnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaddpnlLayout.createSequentialGroup()
                        .addComponent(jTsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaddpnlLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBaddprod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPaddpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsearchsell3)
                    .addComponent(jBsearchsell4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPaddpnl, "card3");

        jPadmininfoo.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane5.setBorder(null);

        jTadmininfo.setAutoCreateRowSorter(true);
        jTadmininfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTadmininfo.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTadmininfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Gender", "Birth Date", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTadmininfo.setGridColor(new java.awt.Color(255, 255, 255));
        jTadmininfo.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane5.setViewportView(jTadmininfo);
        if (jTadmininfo.getColumnModel().getColumnCount() > 0) {
            jTadmininfo.getColumnModel().getColumn(0).setResizable(false);
            jTadmininfo.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTadmininfo.getColumnModel().getColumn(1).setResizable(false);
            jTadmininfo.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTadmininfo.getColumnModel().getColumn(2).setResizable(false);
            jTadmininfo.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTadmininfo.getColumnModel().getColumn(3).setResizable(false);
            jTadmininfo.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTadmininfo.getColumnModel().getColumn(4).setResizable(false);
            jTadmininfo.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jBchangepass.setBackground(new java.awt.Color(241, 223, 169));
        jBchangepass.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBchangepass.setForeground(new java.awt.Color(51, 51, 51));
        jBchangepass.setText("EDIT ADMIN INFO");
        jBchangepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBchangepassMousePressed(evt);
            }
        });
        jBchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchangepassActionPerformed(evt);
            }
        });

        jBchangeadmininfo.setBackground(new java.awt.Color(241, 223, 169));
        jBchangeadmininfo.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBchangeadmininfo.setForeground(new java.awt.Color(51, 51, 51));
        jBchangeadmininfo.setText("CHANGE PASSWORD");
        jBchangeadmininfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBchangeadmininfoMousePressed(evt);
            }
        });
        jBchangeadmininfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchangeadmininfoActionPerformed(evt);
            }
        });

        jBchangepass1.setBackground(new java.awt.Color(241, 223, 169));
        jBchangepass1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBchangepass1.setForeground(new java.awt.Color(51, 51, 51));
        jBchangepass1.setText("ADD ADMIN");
        jBchangepass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBchangepass1MousePressed(evt);
            }
        });
        jBchangepass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchangepass1ActionPerformed(evt);
            }
        });

        jBchangepass2.setBackground(new java.awt.Color(241, 223, 169));
        jBchangepass2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBchangepass2.setForeground(new java.awt.Color(51, 51, 51));
        jBchangepass2.setText("ALL ADMIN");
        jBchangepass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBchangepass2MousePressed(evt);
            }
        });
        jBchangepass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchangepass2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPadmininfooLayout = new javax.swing.GroupLayout(jPadmininfoo);
        jPadmininfoo.setLayout(jPadmininfooLayout);
        jPadmininfooLayout.setHorizontalGroup(
            jPadmininfooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPadmininfooLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPadmininfooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(jPadmininfooLayout.createSequentialGroup()
                        .addComponent(jBchangepass2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBchangepass1))
                    .addGroup(jPadmininfooLayout.createSequentialGroup()
                        .addComponent(jBchangeadmininfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBchangepass)))
                .addContainerGap())
        );
        jPadmininfooLayout.setVerticalGroup(
            jPadmininfooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPadmininfooLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPadmininfooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBchangepass2)
                    .addComponent(jBchangepass1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPadmininfooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBchangepass)
                    .addComponent(jBchangeadmininfo))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jPanel1.add(jPadmininfoo, "card4");

        jPstatistics.setBackground(new java.awt.Color(241, 223, 169));

        jPanel4.setBackground(new java.awt.Color(217, 30, 24));

        jPanel5.setBackground(new java.awt.Color(242, 38, 19));

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Profit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0000");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("The Profit made the last 30 days");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(30, 130, 76));

        jPanel7.setBackground(new java.awt.Color(0, 177, 106));

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Orders");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("00");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total order in last 30 days");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(92, 92, 92))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(142, 68, 173));

        jPanel9.setBackground(new java.awt.Color(155, 89, 182));

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Products");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("000");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Products avalable in the store");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPstatisticsLayout = new javax.swing.GroupLayout(jPstatistics);
        jPstatistics.setLayout(jPstatisticsLayout);
        jPstatisticsLayout.setHorizontalGroup(
            jPstatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPstatisticsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPstatisticsLayout.setVerticalGroup(
            jPstatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPstatisticsLayout.createSequentialGroup()
                .addGroup(jPstatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPstatisticsLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPstatisticsLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPstatisticsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        jPanel1.add(jPstatistics, "card5");

        jPordercard.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(null);

        jTorder.setAutoCreateRowSorter(true);
        jTorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTorder.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer Name", "Quantity", "Date Of Purchase", "Price Befor Discount", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTorder.setGridColor(new java.awt.Color(255, 255, 255));
        jTorder.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane3.setViewportView(jTorder);
        if (jTorder.getColumnModel().getColumnCount() > 0) {
            jTorder.getColumnModel().getColumn(0).setResizable(false);
            jTorder.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTorder.getColumnModel().getColumn(1).setResizable(false);
            jTorder.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTorder.getColumnModel().getColumn(2).setResizable(false);
            jTorder.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTorder.getColumnModel().getColumn(3).setResizable(false);
            jTorder.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTorder.getColumnModel().getColumn(4).setResizable(false);
            jTorder.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTorder.getColumnModel().getColumn(5).setResizable(false);
            jTorder.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        jTsearchbycustname.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jTsearchbycustname.setText("SEARCH BY CUSTOMER NAME");
        jTsearchbycustname.setBorder(null);
        jTsearchbycustname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchbycustnameMousePressed(evt);
            }
        });
        jTsearchbycustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbycustnameActionPerformed(evt);
            }
        });
        jTsearchbycustname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTsearchbycustnameKeyReleased(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jBsearchorder1.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchorder1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchorder1.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchorder1.setText("DELETE ORDER");
        jBsearchorder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchorder1MousePressed(evt);
            }
        });
        jBsearchorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchorder1ActionPerformed(evt);
            }
        });

        jBsearchorder2.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchorder2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchorder2.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchorder2.setText("EDIT ORDER");
        jBsearchorder2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchorder2MousePressed(evt);
            }
        });
        jBsearchorder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchorder2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPordercardLayout = new javax.swing.GroupLayout(jPordercard);
        jPordercard.setLayout(jPordercardLayout);
        jPordercardLayout.setHorizontalGroup(
            jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPordercardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPordercardLayout.createSequentialGroup()
                        .addGroup(jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTsearchbycustname)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212)
                        .addComponent(jBsearchorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBsearchorder1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPordercardLayout.setVerticalGroup(
            jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPordercardLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPordercardLayout.createSequentialGroup()
                        .addComponent(jTsearchbycustname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPordercardLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPordercardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBsearchorder1)
                            .addComponent(jBsearchorder2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPordercard, "card6");

        kGPmain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGPmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGPmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLexitMousePressed

    private void jPsellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsellMousePressed
        // TODO add your handling code he
        setColor(jPsell);
        reset_color(jPlogout);
        reset_color(jPadmininfo);
        reset_color(jPbenefits);
        reset_color(jPaddproduct);
        reset_color(jPorder);
        jLheader.setText("SELL PRODUCT");
        
        CardLayout c =(CardLayout)jPanel1.getLayout();
        c.show(jPanel1, "card2");
        //displayprod2();
    }//GEN-LAST:event_jPsellMousePressed

    private void jPlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlogoutMousePressed
        // TODO add your handling code he
        setColor(jPlogout);
        reset_color(jPsell);
        reset_color(jPadmininfo);
        reset_color(jPbenefits);
        reset_color(jPaddproduct);
        reset_color(jPorder);
        
        LoginF u=new LoginF();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPlogoutMousePressed

    private void jPbenefitsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPbenefitsMousePressed
        // TODO add your handling code here:
        setColor(jPbenefits);
        reset_color(jPsell);
        reset_color(jPlogout);
        reset_color(jPadmininfo);
        reset_color(jPaddproduct);
        reset_color(jPorder);
        jLheader.setText("STATISTICS");
        CardLayout c =(CardLayout)jPanel1.getLayout();
        c.show(jPanel1, "card5");
        int totprice=0,totdiscount=0;
        for(int i=0 ; i< jTorder.getRowCount() ; i++){
            totprice =totprice + Integer.parseInt(jTorder.getValueAt(i, 4).toString());
            totdiscount = totdiscount + Integer.parseInt(jTorder.getValueAt(i, 5).toString());
    }
        jLabel10.setText(" "+Integer.toString(jTaddprod.getRowCount()));
        jLabel6.setText(" "+(totprice - totdiscount));
        jLabel8.setText(" "+Integer.toString(jTorder.getRowCount()));
    }//GEN-LAST:event_jPbenefitsMousePressed

    private void jPaddproductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaddproductMousePressed
        // TODO add your handling code here:
        setColor(jPaddproduct);
        reset_color(jPsell);
        reset_color(jPlogout);
        reset_color(jPadmininfo);
        reset_color(jPbenefits);
        reset_color(jPorder);
        jLheader.setText("ADD PRODUCT");
        jTsearchbyname.setText("SEARCH BY NAME");
        
        CardLayout c =(CardLayout)jPanel1.getLayout();
        c.show(jPanel1, "card3");
        
        displayprod();
              
        
        
    }//GEN-LAST:event_jPaddproductMousePressed

    private void jLexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseEntered
        // TODO add your handling code here:
        jLexittt.setVisible(true);
        jLexittt.setText("Exit");
    }//GEN-LAST:event_jLexitMouseEntered

    private void jLexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseExited
        // TODO add your handling code here:
         jLexittt.setVisible(false);
    }//GEN-LAST:event_jLexitMouseExited

    private void jPadmininfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPadmininfoMousePressed
        // TODO add your handling code here:
        setColor(jPadmininfo);
        reset_color(jPsell);
        reset_color(jPlogout);
        reset_color(jPbenefits);
        reset_color(jPaddproduct);
        reset_color(jPorder);
        jLheader.setText("ADMIN INFO");
        CardLayout c =(CardLayout)jPanel1.getLayout();
        c.show(jPanel1, "card4");
    }//GEN-LAST:event_jPadmininfoMousePressed

    private void jPorderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPorderMousePressed
        // TODO add your handling code here:
        setColor(jPorder);
        reset_color(jPsell);
        reset_color(jPlogout);
        reset_color(jPbenefits);
        reset_color(jPaddproduct);
        reset_color(jPadmininfo);
        jLheader.setText("Order");
        jTsearchbycustname.setText("SEARCH BY CUSTOMER NAME");
        CardLayout c =(CardLayout)jPanel1.getLayout();
        c.show(jPanel1, "card6");
        
        displayorder();
        
    }//GEN-LAST:event_jPorderMousePressed

    private void jBsearchsellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchsellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchsellActionPerformed

    private void jTsearchbynameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchbynameMousePressed
        // TODO add your handling code here:
        jTsearchbyname.setText("");

    }//GEN-LAST:event_jTsearchbynameMousePressed

    private void jTsearchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbynameActionPerformed

    private void jBaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddprodActionPerformed
      
    }//GEN-LAST:event_jBaddprodActionPerformed

    private void jTsearchbycustnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchbycustnameMousePressed
        // TODO add your handling code here:
        jTsearchbycustname.setText("");
    }//GEN-LAST:event_jTsearchbycustnameMousePressed

    private void jTsearchbycustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbycustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbycustnameActionPerformed

    private void jBsearchorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchorder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchorder1ActionPerformed

    private void jBsearchorder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchorder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchorder2ActionPerformed

    private void jBchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchangepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBchangepassActionPerformed

    private void jBchangeadmininfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchangeadmininfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBchangeadmininfoActionPerformed

    private void jBprintbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprintbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBprintbillActionPerformed

    private void jBdeletSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBdeletSActionPerformed

    private void jBsearchsell3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchsell3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchsell3ActionPerformed

    private void jBsearchsell4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchsell4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchsell4ActionPerformed

    private void jBsearchsellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchsellMousePressed
        // TODO add your handling code here:
        SearchProd u = new SearchProd();
        u.setVisible(true);
        if(jCcartype.getSelectedItem().toString() == "ALL"){
            u.displayallprod();
        }
        else{
            u.displayprod(jCcartype.getSelectedItem().toString() , jCcarname.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_jBsearchsellMousePressed

    private void jBdeletSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdeletSMousePressed
        // TODO add your handling code here:
      DefaultTableModel m =(DefaultTableModel) jTSELL.getModel();
      if(jTSELL.getSelectedRowCount()==1){
      m.removeRow(jTSELL.getSelectedRow());
      }else{
            if(jTSELL.getSelectedRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }else{
              JOptionPane.showMessageDialog(this, "Please select Single Row for Delete");
            }
      }
    }//GEN-LAST:event_jBdeletSMousePressed

    private void jBaddprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBaddprodMousePressed
        // TODO add your handling code here:
         AddProd u = new AddProd();
         u.setVisible(true);
    }//GEN-LAST:event_jBaddprodMousePressed

    private void jBsearchsell3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchsell3MousePressed
        // TODO add your handling code here:
        DeleteProdA u = new DeleteProdA();
        u.setVisible(true);
    }//GEN-LAST:event_jBsearchsell3MousePressed

    private void jBsearchsell4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchsell4MousePressed
        // TODO add your handling code here:
        EditOrder u = new EditOrder();
        u.setVisible(true);
    }//GEN-LAST:event_jBsearchsell4MousePressed

    private void jBsearchorder2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchorder2MousePressed
        // TODO add your handling code here:
        EditProdA u=new EditProdA();
        u.setVisible(true);
    }//GEN-LAST:event_jBsearchorder2MousePressed

    private void jBsearchorder1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchorder1MousePressed
        // TODO add your handling code here:
        DeleteOrder u=new DeleteOrder();
        u.setVisible(true);

    }//GEN-LAST:event_jBsearchorder1MousePressed

    private void jBchangeadmininfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBchangeadmininfoMousePressed
        // TODO add your handling code here:
        ChangePass u =new ChangePass();
        u.setVisible(true);
    }//GEN-LAST:event_jBchangeadmininfoMousePressed

    private void jBchangepass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchangepass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBchangepass1ActionPerformed

    private void jBchangepass1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBchangepass1MousePressed
        // TODO add your handling code here:
        AddAdmin u =new AddAdmin();
        u.setVisible(true);
        
        
    }//GEN-LAST:event_jBchangepass1MousePressed

    private void jBchangepassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBchangepassMousePressed
        // TODO add your handling code here:
        EditAdmin u=new EditAdmin();
        u.setVisible(true);
    }//GEN-LAST:event_jBchangepassMousePressed

    private void jBchangepass2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBchangepass2MousePressed
        // TODO add your handling code here:
        displayadmin();
    }//GEN-LAST:event_jBchangepass2MousePressed

    private void jBchangepass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchangepass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBchangepass2ActionPerformed

    private void jCcartypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcartypeActionPerformed
        // TODO add your handling code here:
        
        jCcarname.removeAllItems();
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
        if(this.jCcartype.getSelectedItem().toString() == "ALL"){
             jCcarname.setEnabled(false);
        }
        else{
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");

                String strStmt="select * from CAR where CAR_TYPE='"+this.jCcartype.getSelectedItem().toString()+"'";
                PreparedStatement pst= conn.prepareStatement(strStmt);


                rs = pst.executeQuery();

                while (rs.next()) {          
                     jCcarname.addItem(rs.getString("car_name"));
                }
                jCcarname.setEnabled(true);
                conn.setAutoCommit(false);
                conn.commit();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jCcartypeActionPerformed

    private void jCcarnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcarnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcarnameActionPerformed

    private void jTsearchbynameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTsearchbynameKeyReleased
        // TODO add your handling code here:
        
        DefaultTableModel table= (DefaultTableModel)jTaddprod.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        jTaddprod.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTsearchbyname.getText(),1));
        
        
        
       
    }//GEN-LAST:event_jTsearchbynameKeyReleased

    private void jTsearchbycustnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTsearchbycustnameKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table= (DefaultTableModel)jTorder.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        jTorder.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTsearchbycustname.getText(),1));
    }//GEN-LAST:event_jTsearchbycustnameKeyReleased

    private void jBprintbillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBprintbillMousePressed
        // TODO add your handling code here:
        if(jTSELL.getRowCount() != 0){
        PrintBill u =new PrintBill();
        u.setVisible(true);
        u.addtojtxtf(jTSELL);
        }
        else {
        JOptionPane.showMessageDialog(this, "Please add Products ");
        }
    }//GEN-LAST:event_jBprintbillMousePressed

    void setColor(JPanel pnl ){
    pnl.setBackground(new Color(45,72,77));
    }
    
    void reset_color(JPanel pnl){
     pnl.setBackground(new Color(234,199,94));
    }
    void displayprod(){
     String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from product";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel tblmodel=(DefaultTableModel) jTaddprod.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
            String ID = String.valueOf(rs.getInt("prod_id"));
            String name=rs.getString("prod_name");
            String Q = String.valueOf(rs.getInt("Quantity"));
            String DateofP= rs.getString("Date_of_Purchase");
            String Price=String.valueOf(rs.getInt("price"));
            
            String tbData[]={ID,name,Q,DateofP,Price};
            tblmodel.addRow(tbData);
            
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void displayprod2(){
     String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from product";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel tblmodel=(DefaultTableModel) jTSELL.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
            String ID = String.valueOf(rs.getInt("prod_id"));
            String name=rs.getString("prod_name");
            String Q = String.valueOf(rs.getInt("Quantity"));
            String DateofP= rs.getString("Date_of_Purchase");
            String Price=String.valueOf(rs.getInt("price"));
            
            String tbData[]={ID,name,Q,Price};
            tblmodel.addRow(tbData);
            
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void displayadmin(){
     String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from admininfo";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel tblmodel=(DefaultTableModel) jTadmininfo.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
            String ID = String.valueOf(rs.getInt("id"));
            String uname=rs.getString("username");
            String G = rs.getString("gender");
            String DateofP= rs.getString("birth_Date");
            String address=rs.getString("address");
            String pass = rs.getString("password");
            
            
            String tbData[]={ID,uname,G,DateofP,address};
            tblmodel.addRow(tbData);
            
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    public static void addtotablesell(Object[] dataRow){
    DefaultTableModel m =(DefaultTableModel)jTSELL.getModel();
    m.addRow(dataRow);
    }
    public static boolean existsInTable(int id) {
        int rowCount = jTSELL.getRowCount();
        int rowEntry = 0;
        for (int i = 0; i < rowCount; i++) {               
                     rowEntry =Integer.parseInt( jTSELL.getValueAt(i, 0).toString());
                    if (rowEntry == id) {
                         return true;
                    }
        }
         return false;
    }
    void displayorder(){
     String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from orderinfo";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel tblmodel=(DefaultTableModel) jTorder.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
            String ID = String.valueOf(rs.getInt("order_id"));
            String name=rs.getString("customer_name");
            String Q = String.valueOf(rs.getInt("Quantity"));
            String DateofP= rs.getString("Date_of_Purchase");
            String Price=String.valueOf(rs.getInt("price"));
            String dis=String.valueOf(rs.getInt("discount"));
            
            String tbData[]={ID,name,Q,DateofP,Price,dis};
            tblmodel.addRow(tbData);
            
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void setv(){
         jPorder.setVisible(false);
         jPbenefits.setVisible(false);
         jPadmininfo.setVisible(false);
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaddprod;
    private javax.swing.JButton jBchangeadmininfo;
    private javax.swing.JButton jBchangepass;
    private javax.swing.JButton jBchangepass1;
    private javax.swing.JButton jBchangepass2;
    private javax.swing.JButton jBdeletS;
    private javax.swing.JButton jBprintbill;
    private javax.swing.JButton jBsearchorder1;
    private javax.swing.JButton jBsearchorder2;
    private javax.swing.JButton jBsearchsell;
    private javax.swing.JButton jBsearchsell3;
    private javax.swing.JButton jBsearchsell4;
    private javax.swing.JComboBox<String> jCcarname;
    private javax.swing.JComboBox<String> jCcartype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLaddpro;
    private javax.swing.JLabel jLadmininfo;
    private javax.swing.JLabel jLadminninfo;
    private javax.swing.JLabel jLbenefits;
    private javax.swing.JLabel jLcarname;
    private javax.swing.JLabel jLcartype;
    private javax.swing.JLabel jLexit;
    private javax.swing.JLabel jLexittt;
    private javax.swing.JLabel jLheader;
    private javax.swing.JLabel jLiconaddpro;
    private javax.swing.JLabel jLiconbenefits;
    private javax.swing.JLabel jLiconorder;
    private javax.swing.JLabel jLiconsell;
    private javax.swing.JLabel jLlogout;
    private javax.swing.JLabel jLorder;
    private javax.swing.JLabel jLsell;
    private javax.swing.JPanel jPaddpnl;
    private javax.swing.JPanel jPaddproduct;
    private javax.swing.JPanel jPadmininfo;
    private javax.swing.JPanel jPadmininfoo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPbenefits;
    private javax.swing.JPanel jPlogout;
    private javax.swing.JPanel jPorder;
    private javax.swing.JPanel jPordercard;
    private javax.swing.JPanel jPsell;
    private javax.swing.JPanel jPsellpnl;
    private javax.swing.JPanel jPstatistics;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private static javax.swing.JTable jTSELL;
    private javax.swing.JTable jTaddprod;
    private javax.swing.JTable jTadmininfo;
    private javax.swing.JTable jTorder;
    private javax.swing.JTextField jTsearchbycustname;
    private javax.swing.JTextField jTsearchbyname;
    private com.k33ptoo.components.KGradientPanel kGPmain;
    private com.k33ptoo.components.KGradientPanel kGPright;
    private com.k33ptoo.components.KGradientPanel kGPside;
    // End of variables declaration//GEN-END:variables
}
