/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author ameer
 */
public class DeleteProdA extends javax.swing.JFrame {

    /**
     * Creates new form DeleteProdS
     */
    public DeleteProdA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLheader = new javax.swing.JLabel();
        jLheader1 = new javax.swing.JLabel();
        jTdeletefeilde = new javax.swing.JTextField();
        jBdeletecolmn = new javax.swing.JButton();
        jLmsg = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jLheader.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader.setText("Enter Serial ID");

        jLheader1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader1.setText("DELETE PRODUCT");

        jTdeletefeilde.setBackground(new java.awt.Color(45, 72, 77));
        jTdeletefeilde.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTdeletefeilde.setForeground(new java.awt.Color(255, 255, 255));
        jTdeletefeilde.setBorder(null);
        jTdeletefeilde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdeletefeildeActionPerformed(evt);
            }
        });

        jBdeletecolmn.setBackground(new java.awt.Color(241, 223, 169));
        jBdeletecolmn.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBdeletecolmn.setForeground(new java.awt.Color(51, 51, 51));
        jBdeletecolmn.setText("DELETE");
        jBdeletecolmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletecolmnActionPerformed(evt);
            }
        });

        jLmsg.setBackground(new java.awt.Color(241, 223, 169));
        jLmsg.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLmsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLheader1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLheader)
                        .addGap(34, 34, 34)
                        .addComponent(jTdeletefeilde, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBdeletecolmn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLheader1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLheader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTdeletefeilde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBdeletecolmn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTdeletefeildeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdeletefeildeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdeletefeildeActionPerformed

    private void jBdeletecolmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletecolmnActionPerformed
        // TODO add your handling code here:
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
        int id=0;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            if(!this.jTdeletefeilde.getText().isEmpty()){
                String strStmt="delete from product where  PROD_ID = ? ";
                String strStmt3="delete from prodcar where  PROD_ID = ? ";
                String strStmt2="select * from product where PROD_ID='"+this.jTdeletefeilde.getText()+"'";
                PreparedStatement pst= conn.prepareStatement(strStmt);
                PreparedStatement pstsearch= conn.prepareStatement(strStmt2);
                PreparedStatement pstd= conn.prepareStatement(strStmt3);

                rs = pstsearch.executeQuery();

                if (rs.next()) {          
                     id = rs.getInt("prod_id");
                }

                if(id == Integer.parseInt(jTdeletefeilde.getText().trim())){

                    pst.setInt(1, Integer.parseInt(jTdeletefeilde.getText().trim()));
                    pstd.setInt(1, Integer.parseInt(jTdeletefeilde.getText().trim()));
                    pst.executeUpdate();
                    pstd.executeUpdate();
                    jLmsg.setText("The product is deleted");

                }
                else{jLmsg.setText("The product does not exist");}
            }else{jLmsg.setText("Please enter Serial ID");}
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jBdeletecolmnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProdA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdeletecolmn;
    private javax.swing.JLabel jLheader;
    private javax.swing.JLabel jLheader1;
    private javax.swing.JLabel jLmsg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTdeletefeilde;
    // End of variables declaration//GEN-END:variables
}
