/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ameer
 */
public class DeleteOrder extends javax.swing.JFrame {

    /**
     * Creates new form DeleteProdS
     */
    public DeleteOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLheader = new javax.swing.JLabel();
        jLheader1 = new javax.swing.JLabel();
        jTdeleteorder = new javax.swing.JTextField();
        jBsearchaddprod = new javax.swing.JButton();
        jLmsg = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jLheader.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader.setText("Enter Order ID");

        jLheader1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader1.setText("DELETE ORDER");

        jTdeleteorder.setBackground(new java.awt.Color(45, 72, 77));
        jTdeleteorder.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTdeleteorder.setForeground(new java.awt.Color(255, 255, 255));
        jTdeleteorder.setBorder(null);
        jTdeleteorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdeleteorderActionPerformed(evt);
            }
        });

        jBsearchaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod.setText("DELETE");
        jBsearchaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprodActionPerformed(evt);
            }
        });

        jLmsg.setBackground(new java.awt.Color(241, 223, 169));
        jLmsg.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLmsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBsearchaddprod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLheader1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLheader)
                        .addGap(33, 33, 33)
                        .addComponent(jTdeleteorder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLheader1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTdeleteorder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsearchaddprod)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTdeleteorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdeleteorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdeleteorderActionPerformed

    private void jBsearchaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprodActionPerformed
        // TODO add your handling code here:
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
        int id=0;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            if(!this.jTdeleteorder.getText().isEmpty()){
                String strStmt="delete from orderinfo where  ORDER_ID = ? ";
                String strStmt2="select * from orderinfo where ORDER_ID='"+this.jTdeleteorder.getText()+"'";
                PreparedStatement pst= conn.prepareStatement(strStmt);
                PreparedStatement pstsearch= conn.prepareStatement(strStmt2);

                rs = pstsearch.executeQuery();

                if (rs.next()) {          
                     id = rs.getInt("order_id");
                }

                if(id == Integer.parseInt(jTdeleteorder.getText().trim())){

                    pst.setInt(1, Integer.parseInt(jTdeleteorder.getText().trim()));
                    pst.executeUpdate();
                    jLmsg.setText("The order is deleted");

                }
                else{jLmsg.setText("The Order does not exist");}
            }else{jLmsg.setText("Please enter Order Id");}
            
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBsearchaddprodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsearchaddprod;
    private javax.swing.JLabel jLheader;
    private javax.swing.JLabel jLheader1;
    private javax.swing.JLabel jLmsg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTdeleteorder;
    // End of variables declaration//GEN-END:variables
}
