/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ameer
 */
public class EditOrder extends javax.swing.JFrame {

    /**
     * Creates new form EditProdA
     */
    public EditOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTsearchbyserialid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jBsearchaddprod = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLheader2 = new javax.swing.JLabel();
        jTprodname = new javax.swing.JTextField();
        jTQ = new javax.swing.JTextField();
        jLheader3 = new javax.swing.JLabel();
        jLheader4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTprice = new javax.swing.JTextField();
        jLheader5 = new javax.swing.JLabel();
        jBsearchaddprod1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jTsearchbyserialid.setBackground(new java.awt.Color(241, 223, 169));
        jTsearchbyserialid.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTsearchbyserialid.setBorder(null);
        jTsearchbyserialid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchbyserialidMousePressed(evt);
            }
        });
        jTsearchbyserialid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyserialidActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(241, 223, 169));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH BY SERIAL ID");

        jBsearchaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod.setText("Search");
        jBsearchaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprodMousePressed(evt);
            }
        });
        jBsearchaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprodActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(241, 223, 169));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setText("EDIT PRODUCT");

        jLheader2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader2.setText("Product Name :");

        jTprodname.setBackground(new java.awt.Color(45, 72, 77));
        jTprodname.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTprodname.setForeground(new java.awt.Color(255, 255, 255));
        jTprodname.setBorder(null);
        jTprodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTprodnameActionPerformed(evt);
            }
        });

        jTQ.setBackground(new java.awt.Color(45, 72, 77));
        jTQ.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTQ.setForeground(new java.awt.Color(255, 255, 255));
        jTQ.setBorder(null);
        jTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQActionPerformed(evt);
            }
        });

        jLheader3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader3.setText("Quantity :");

        jLheader4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader4.setText("Date Of Purchase :");

        jDateChooser1.setBackground(new java.awt.Color(45, 72, 77));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jTprice.setBackground(new java.awt.Color(45, 72, 77));
        jTprice.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTprice.setForeground(new java.awt.Color(255, 255, 255));
        jTprice.setBorder(null);
        jTprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpriceActionPerformed(evt);
            }
        });

        jLheader5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader5.setText("Price :");

        jBsearchaddprod1.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jBsearchaddprod1.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod1.setText("Save Update");
        jBsearchaddprod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprod1MousePressed(evt);
            }
        });
        jBsearchaddprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprod1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(241, 223, 169));
        jLabel3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3)
                    .addComponent(jTsearchbyserialid, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsearchaddprod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jBsearchaddprod1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLheader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLheader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLheader5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTprodname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTprice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTsearchbyserialid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBsearchaddprod))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTprodname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLheader4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheader5)
                    .addComponent(jTprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBsearchaddprod1)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTsearchbyserialidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchbyserialidMousePressed
        // TODO add your handling code here:
        jTsearchbyserialid.setText("");
    }//GEN-LAST:event_jTsearchbyserialidMousePressed

    private void jTsearchbyserialidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyserialidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyserialidActionPerformed

    private void jBsearchaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprodActionPerformed

    private void jTprodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTprodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTprodnameActionPerformed

    private void jTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQActionPerformed

    private void jTpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpriceActionPerformed

    private void jBsearchaddprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprod1ActionPerformed

    private void jBsearchaddprod1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprod1MousePressed
        // TODO add your handling code here:
       
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
        int id=0;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            if(!this.jTsearchbyserialid.getText().isEmpty()){
                String strStmt="delete from product where  PROD_ID = ? ";
                String strStmt2="select * from product where PROD_ID='"+this.jTsearchbyserialid.getText()+"'";
                String strStmt3="insert into product (PROD_ID, PROD_NAME, QUANTITY,DATE_OF_PURCHASE,PRICE) values (?,?,?,to_date(?, 'dd-MM-yyyy'),?)";
                PreparedStatement pst= conn.prepareStatement(strStmt);
                PreparedStatement pstsearch= conn.prepareStatement(strStmt2);
                PreparedStatement pst3= conn.prepareStatement(strStmt3);

                rs = pstsearch.executeQuery();

                if (rs.next()) {          
                     id = rs.getInt("prod_id");
                }

                if(id == Integer.parseInt(jTsearchbyserialid.getText().trim())){

                    pst.setInt(1, Integer.parseInt(jTsearchbyserialid.getText().trim()));
                    pst.executeUpdate();
                }

                pst3.setInt(1, Integer.parseInt(jTsearchbyserialid.getText().trim()));

                pst3.setString(2, jTprodname.getText());

                pst3.setInt(3, Integer.parseInt(jTQ.getText().trim()));

                SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                String date= sdf.format(jDateChooser1.getDate());
                pst3.setString(4, date);

                pst3.setInt(5,Integer.parseInt(jTprice.getText().trim()));
                pst3.executeUpdate();       
                 jLabel3.setText("The product in changed");
            }else{
                 jLabel3.setText("Please enter Serial ID and Search");
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jBsearchaddprod1MousePressed

    private void jBsearchaddprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprodMousePressed
        // TODO add your handling code here:
          String url="jdbc:oracle:thin:@localhost:1521:xe";
          ResultSet rs = null;
       
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
               if(!this.jTsearchbyserialid.getText().isEmpty()){
                    String strStmt="select * from product where PROD_ID='"+this.jTsearchbyserialid.getText()+"'";
                    PreparedStatement pst= conn.prepareStatement(strStmt);


                    rs = pst.executeQuery();

                    if (rs.next()) {       
                        jTprodname.setText(rs.getString("prod_name"));
                        jTQ.setText(rs.getString("quantity"));
                        jDateChooser1.setDate(rs.getDate("date_of_purchase"));
                        jTprice.setText(rs.getString("price"));
                    }
                    if(jTprodname.getText().isEmpty() && jTQ.getText().isEmpty() && jTprice.getText().isEmpty() ){
                         jLabel3.setText("The Product does not exist");
                    }
                    
               }else{
                   jLabel3.setText("Please enter Serial Id");
                   jTprodname.setText("");
                   jTQ.setText("");
                   jDateChooser1.setDate(null);
                   jTprice.setText("");
               }
                conn.setAutoCommit(false);
                conn.commit();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBsearchaddprodMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsearchaddprod;
    private javax.swing.JButton jBsearchaddprod1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLheader2;
    private javax.swing.JLabel jLheader3;
    private javax.swing.JLabel jLheader4;
    private javax.swing.JLabel jLheader5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTQ;
    private javax.swing.JTextField jTprice;
    private javax.swing.JTextField jTprodname;
    private javax.swing.JTextField jTsearchbyserialid;
    // End of variables declaration//GEN-END:variables
}
