/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ameer
 */
public class EditProdA extends javax.swing.JFrame {

    /**
     * Creates new form EditProdA
     */
    public EditProdA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTsearchorderid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jBsearchaddprod = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLheader2 = new javax.swing.JLabel();
        jTcustname = new javax.swing.JTextField();
        jTQ = new javax.swing.JTextField();
        jLheader3 = new javax.swing.JLabel();
        jLheader4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTprice = new javax.swing.JTextField();
        jLheader5 = new javax.swing.JLabel();
        jBsearchaddprod1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLdiscount = new javax.swing.JLabel();
        jTdiscount = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jTsearchorderid.setBackground(new java.awt.Color(241, 223, 169));
        jTsearchorderid.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTsearchorderid.setBorder(null);
        jTsearchorderid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchorderidMousePressed(evt);
            }
        });
        jTsearchorderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchorderidActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(241, 223, 169));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH BY ORDER ID");

        jBsearchaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod.setText("Search");
        jBsearchaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprodMousePressed(evt);
            }
        });
        jBsearchaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprodActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(241, 223, 169));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setText("EDIT ORDER");

        jLheader2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader2.setText("Customer Name :");

        jTcustname.setBackground(new java.awt.Color(45, 72, 77));
        jTcustname.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTcustname.setForeground(new java.awt.Color(255, 255, 255));
        jTcustname.setBorder(null);
        jTcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcustnameActionPerformed(evt);
            }
        });

        jTQ.setBackground(new java.awt.Color(45, 72, 77));
        jTQ.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTQ.setForeground(new java.awt.Color(255, 255, 255));
        jTQ.setBorder(null);
        jTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQActionPerformed(evt);
            }
        });

        jLheader3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader3.setText("Quantity :");

        jLheader4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader4.setText("Date Of Purchase :");

        jDateChooser1.setBackground(new java.awt.Color(45, 72, 77));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jTprice.setBackground(new java.awt.Color(45, 72, 77));
        jTprice.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTprice.setForeground(new java.awt.Color(255, 255, 255));
        jTprice.setBorder(null);
        jTprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpriceActionPerformed(evt);
            }
        });

        jLheader5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader5.setText("Price :");

        jBsearchaddprod1.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jBsearchaddprod1.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod1.setText("Save Update");
        jBsearchaddprod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprod1MousePressed(evt);
            }
        });
        jBsearchaddprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprod1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(241, 223, 169));
        jLabel3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));

        jLdiscount.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLdiscount.setText("Discount :");

        jTdiscount.setBackground(new java.awt.Color(45, 72, 77));
        jTdiscount.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTdiscount.setForeground(new java.awt.Color(255, 255, 255));
        jTdiscount.setBorder(null);
        jTdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator3)
                                    .addComponent(jTsearchorderid, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(jBsearchaddprod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLheader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLheader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLheader5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTcustname, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTprice, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTQ, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jBsearchaddprod1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTsearchorderid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsearchaddprod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcustname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLheader4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheader5)
                    .addComponent(jTprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdiscount)
                    .addComponent(jTdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsearchaddprod1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTsearchorderidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchorderidMousePressed
        // TODO add your handling code here:
        jTsearchorderid.setText("");
    }//GEN-LAST:event_jTsearchorderidMousePressed

    private void jTsearchorderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchorderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchorderidActionPerformed

    private void jBsearchaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprodActionPerformed

    private void jTcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcustnameActionPerformed

    private void jTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQActionPerformed

    private void jTpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpriceActionPerformed

    private void jBsearchaddprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprod1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jBsearchaddprod1ActionPerformed

    private void jBsearchaddprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprodMousePressed
        // TODO add your handling code here:
          String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
       
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
                
                 if(!this.jTsearchorderid.getText().isEmpty()){
                    String strStmt="select * from orderinfo where ORDER_ID='"+this.jTsearchorderid.getText()+"'";
                    PreparedStatement pst= conn.prepareStatement(strStmt);


                    rs = pst.executeQuery();

                    if (rs.next()) {       
                        jTcustname.setText(rs.getString("customer_name"));
                        jTQ.setText(rs.getString("quantity"));
                        jDateChooser1.setDate(rs.getDate("date_of_purchase"));
                        jTprice.setText(rs.getString("price"));
                        jTdiscount.setText(rs.getString("discount"));
                       
                    }
                    if(jTcustname.getText().isEmpty() && jTQ.getText().isEmpty() && jTprice.getText().isEmpty() && jTdiscount.getText().isEmpty() ){
                        jLabel3.setText("The Order does not exist");
                    }
                 }else{
                   jLabel3.setText("Please enter Order Id");
                   jTcustname.setText("");
                   jTQ.setText("");
                   jDateChooser1.setDate(null);
                   jTprice.setText("");
               }
                conn.setAutoCommit(false);
                conn.commit();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBsearchaddprodMousePressed

    private void jTdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdiscountActionPerformed

    private void jBsearchaddprod1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprod1MousePressed
        // TODO add your handling code here:
        
          String url="jdbc:oracle:thin:@localhost:1521:xe";
          ResultSet rs = null;
          String custmername=jTcustname.getText();
          if(!jTsearchorderid.getText().isEmpty() && !jTQ.getText().isEmpty() && !jTprice.getText().isEmpty() && !jTdiscount.getText().isEmpty() ){
                int id=Integer.parseInt(jTsearchorderid.getText().trim()),q=Integer.parseInt(jTQ.getText().trim()),price=Integer.parseInt(jTprice.getText().trim());
                int discount = Integer.parseInt(jTdiscount.getText().trim());

                try {
                    DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                    Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
                    

                    String strStmt3="UPDATE orderinfo SET customer_name= ?,quantity=?,date_of_purchase=to_date(?, 'dd-MM-yyyy'),price=?,discount=? WHERE order_id= ?";
                    PreparedStatement pst3= conn.prepareStatement(strStmt3);

                        pst3.setString(1, custmername);
                        pst3.setInt(2, q);

                        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                        String date= sdf.format(jDateChooser1.getDate());
                        pst3.setString(3, date);

                        pst3.setInt(4, price);
                         pst3.setInt(5, discount);
                        pst3.setInt(6, id);

                        pst3.executeUpdate();
                        jLabel3.setText("The order is changed");
                    

                    conn.setAutoCommit(false);
                    conn.commit();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
                }
          }else{
                        jLabel3.setText("Please enter Order ID and Search");
                    }
    }//GEN-LAST:event_jBsearchaddprod1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProdA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProdA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsearchaddprod;
    private javax.swing.JButton jBsearchaddprod1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLdiscount;
    private javax.swing.JLabel jLheader2;
    private javax.swing.JLabel jLheader3;
    private javax.swing.JLabel jLheader4;
    private javax.swing.JLabel jLheader5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTQ;
    private javax.swing.JTextField jTcustname;
    private javax.swing.JTextField jTdiscount;
    private javax.swing.JTextField jTprice;
    private javax.swing.JTextField jTsearchorderid;
    // End of variables declaration//GEN-END:variables
}
