/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ameer
 */
public class EditAdmin extends javax.swing.JFrame {

    /**
     * Creates new form EditProdA
     */
    public EditAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTsearchbycustname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jBsearchaddprod = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLheader2 = new javax.swing.JLabel();
        jTsearchbyname5 = new javax.swing.JTextField();
        jLheader3 = new javax.swing.JLabel();
        jLheader4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTsearchbyname3 = new javax.swing.JTextField();
        jLheader5 = new javax.swing.JLabel();
        jBsearchaddprod1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jTsearchbycustname.setBackground(new java.awt.Color(241, 223, 169));
        jTsearchbycustname.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTsearchbycustname.setBorder(null);
        jTsearchbycustname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchbycustnameMousePressed(evt);
            }
        });
        jTsearchbycustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbycustnameActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(241, 223, 169));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH BY ID");

        jBsearchaddprod.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jBsearchaddprod.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod.setText("Search");
        jBsearchaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprodMousePressed(evt);
            }
        });
        jBsearchaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprodActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(241, 223, 169));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setText("EDIT ADMIN");

        jLheader2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader2.setText("User Name :");

        jTsearchbyname5.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname5.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname5.setBorder(null);
        jTsearchbyname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname5ActionPerformed(evt);
            }
        });

        jLheader3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader3.setText("Gender :");

        jLheader4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader4.setText("Birth Date :");

        jDateChooser1.setBackground(new java.awt.Color(45, 72, 77));
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jTsearchbyname3.setBackground(new java.awt.Color(45, 72, 77));
        jTsearchbyname3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTsearchbyname3.setForeground(new java.awt.Color(255, 255, 255));
        jTsearchbyname3.setBorder(null);
        jTsearchbyname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbyname3ActionPerformed(evt);
            }
        });

        jLheader5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLheader5.setText("Address :");

        jBsearchaddprod1.setBackground(new java.awt.Color(241, 223, 169));
        jBsearchaddprod1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jBsearchaddprod1.setForeground(new java.awt.Color(51, 51, 51));
        jBsearchaddprod1.setText("Save Update");
        jBsearchaddprod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBsearchaddprod1MousePressed(evt);
            }
        });
        jBsearchaddprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchaddprod1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(241, 223, 169));
        jLabel3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));

        jRadioButton1.setBackground(new java.awt.Color(241, 223, 169));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jRadioButton1.setText("Male");

        jRadioButton2.setBackground(new java.awt.Color(241, 223, 169));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3)
                    .addComponent(jTsearchbycustname, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsearchaddprod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLheader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLheader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLheader5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTsearchbyname5)
                            .addComponent(jTsearchbyname3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBsearchaddprod1))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTsearchbycustname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBsearchaddprod))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTsearchbyname5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLheader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheader3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLheader4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheader5)
                    .addComponent(jTsearchbyname3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsearchaddprod1)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTsearchbycustnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchbycustnameMousePressed
        // TODO add your handling code here:
        jTsearchbycustname.setText("");
    }//GEN-LAST:event_jTsearchbycustnameMousePressed

    private void jTsearchbycustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbycustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbycustnameActionPerformed

    private void jBsearchaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprodActionPerformed

    private void jTsearchbyname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname5ActionPerformed

    private void jTsearchbyname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbyname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbyname3ActionPerformed

    private void jBsearchaddprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchaddprod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsearchaddprod1ActionPerformed

    private void jBsearchaddprod1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprod1MousePressed
        // TODO add your handling code here:
          String url="jdbc:oracle:thin:@localhost:1521:xe";
          ResultSet rs = null;
          String username=jTsearchbyname5.getText(),add=jTsearchbyname3.getText(),gen;
          if(jRadioButton1.isSelected()){
              gen="male";
          }else{gen ="female";}
          
          if(!jTsearchbycustname.getText().isEmpty() && !jTsearchbyname5.getText().isEmpty() && !jTsearchbyname3.getText().isEmpty()){
              
            int id=Integer.parseInt(jTsearchbycustname.getText().trim());
              try {
                  DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                  Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");

                  String strStmt3="UPDATE admininfo SET username= ?,gender=?,birth_date=to_date(?, 'dd-MM-yyyy'),address=? WHERE id= ?";
                  PreparedStatement pst3= conn.prepareStatement(strStmt3);

                      pst3.setString(1, username);
                      pst3.setString(2, gen);

                      SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                      String date= sdf.format(jDateChooser1.getDate());
                      pst3.setString(3, date);

                      pst3.setString(4, add);
                      pst3.setInt(5, id);

                      pst3.executeUpdate();
                      jLabel3.setText("The admin is changed");


                  conn.setAutoCommit(false);
                  conn.commit();
                  conn.close();
              } catch (SQLException ex) {
                  Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
              }
          }else{
                        jLabel3.setText("Please enter ID and Search");
                    }
       
    }//GEN-LAST:event_jBsearchaddprod1MousePressed

    private void jBsearchaddprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsearchaddprodMousePressed
        // TODO add your handling code here:
        
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs = null;
       
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
                if(!this.jTsearchbycustname.getText().isEmpty()){
                    String strStmt="select * from admininfo where ID='"+this.jTsearchbycustname.getText()+"'";
                    PreparedStatement pst= conn.prepareStatement(strStmt);


                    rs = pst.executeQuery();

                    if (rs.next()) {       
                        jTsearchbyname5.setText(rs.getString("username"));
                        if(rs.getString("gender")=="male"){
                            jRadioButton1.setSelected(true);
                        }else{
                            jRadioButton2.setSelected(true);
                        }
                        jDateChooser1.setDate(rs.getDate("birth_date"));
                        jTsearchbyname3.setText(rs.getString("address"));

                    }
                    if(jTsearchbyname5.getText().isEmpty() && jTsearchbyname3.getText().isEmpty() ){
                         jLabel3.setText("The Admin does not exist");
                    }
                }else{
                   jLabel3.setText("Please enter ID");
                   jTsearchbyname5.setText("");
                   jRadioButton1.setSelected(false);
                   jDateChooser1.setDate(null);
                   jTsearchbyname3.setText("");
               }
                conn.setAutoCommit(false);
                conn.commit();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBsearchaddprodMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBsearchaddprod;
    private javax.swing.JButton jBsearchaddprod1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLheader2;
    private javax.swing.JLabel jLheader3;
    private javax.swing.JLabel jLheader4;
    private javax.swing.JLabel jLheader5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTsearchbycustname;
    private javax.swing.JTextField jTsearchbyname3;
    private javax.swing.JTextField jTsearchbyname5;
    // End of variables declaration//GEN-END:variables
}
