/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.Clock.system;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ameer
 */
public class LoginF extends javax.swing.JFrame {

    /**
     * Creates new form LoginF
     */
    public LoginF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPmainpnl = new javax.swing.JPanel();
        jPleftpnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProghtpnl = new javax.swing.JPanel();
        jTusername = new javax.swing.JTextField();
        jPasswordF = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLiconuser = new javax.swing.JLabel();
        jLiconpass = new javax.swing.JLabel();
        jPloginpnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLexitpnl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\Caggyttytytpture.PNG")); // NOI18N

        javax.swing.GroupLayout jPleftpnlLayout = new javax.swing.GroupLayout(jPleftpnl);
        jPleftpnl.setLayout(jPleftpnlLayout);
        jPleftpnlLayout.setHorizontalGroup(
            jPleftpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPleftpnlLayout.setVerticalGroup(
            jPleftpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jProghtpnl.setBackground(new java.awt.Color(241, 223, 169));
        jProghtpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTusername.setBackground(new java.awt.Color(241, 223, 169));
        jTusername.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jTusername.setText("Username");
        jTusername.setBorder(null);
        jTusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTusernameMousePressed(evt);
            }
        });
        jTusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTusernameActionPerformed(evt);
            }
        });
        jProghtpnl.add(jTusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, 180, 30));

        jPasswordF.setBackground(new java.awt.Color(241, 223, 169));
        jPasswordF.setText("Password");
        jPasswordF.setBorder(null);
        jPasswordF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFMousePressed(evt);
            }
        });
        jPasswordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFActionPerformed(evt);
            }
        });
        jProghtpnl.add(jPasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jProghtpnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jProghtpnl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 10));

        jLiconuser.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\user.png")); // NOI18N
        jProghtpnl.add(jLiconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        jLiconpass.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\lock.png")); // NOI18N
        jProghtpnl.add(jLiconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jPloginpnl.setBackground(new java.awt.Color(241, 223, 169));
        jPloginpnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPloginpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPloginpnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPloginpnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPloginpnlMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel4.setText("            Log In");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPloginpnlLayout = new javax.swing.GroupLayout(jPloginpnl);
        jPloginpnl.setLayout(jPloginpnlLayout);
        jPloginpnlLayout.setHorizontalGroup(
            jPloginpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPloginpnlLayout.setVerticalGroup(
            jPloginpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jProghtpnl.add(jPloginpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 40));

        jLexitpnl.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Ameer NAJAH\\DBGTCAR\\src\\dbgtcar\\imagess\\cross (1).png")); // NOI18N
        jLexitpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLexitpnlMousePressed(evt);
            }
        });
        jProghtpnl.add(jLexitpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, 20));

        jLabel2.setBackground(new java.awt.Color(241, 223, 169));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jProghtpnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, 20));

        javax.swing.GroupLayout jPmainpnlLayout = new javax.swing.GroupLayout(jPmainpnl);
        jPmainpnl.setLayout(jPmainpnlLayout);
        jPmainpnlLayout.setHorizontalGroup(
            jPmainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmainpnlLayout.createSequentialGroup()
                .addComponent(jPleftpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProghtpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPmainpnlLayout.setVerticalGroup(
            jPmainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPleftpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProghtpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTusernameActionPerformed

    private void jPasswordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFActionPerformed

    private void jLexitpnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitpnlMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLexitpnlMousePressed

    private void jTusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTusernameMousePressed
        // TODO add your handling code here:
        jTusername.setText("");
      
    }//GEN-LAST:event_jTusernameMousePressed

    private void jPloginpnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPloginpnlMouseEntered
        // TODO add your handling code here:
        jPloginpnl.setBackground(new Color(45,72,77));
        jLabel4.setForeground(Color.white);
        
    }//GEN-LAST:event_jPloginpnlMouseEntered

    private void jPloginpnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPloginpnlMouseExited
        // TODO add your handling code here:
        jPloginpnl.setBackground(new Color(241,223,169));
         jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_jPloginpnlMouseExited

    private void jPloginpnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPloginpnlMousePressed
        // TODO add your handling code here:
        AdminInterface u=new AdminInterface();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPloginpnlMousePressed

    private void jPasswordFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFMousePressed
        // TODO add your handling code here:
        jPasswordF.setText("");
    }//GEN-LAST:event_jPasswordFMousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        
          String url="jdbc:oracle:thin:@localhost:1521:xe";
          ResultSet rs = null;
          
          String pass2 =new String(jPasswordF.getPassword());
          String unamet=jTusername.getText();
          AdminInterface u =new AdminInterface();
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");

               // String strStmt="select * from admininfo where USERNAME='"+jTusername.getText()+"'";
                String strStmt="select * from ADMININFO";
                PreparedStatement pst= conn.prepareStatement(strStmt);
                rs = pst.executeQuery();

                while (rs.next()) {   
                    String uname=rs.getString("username");
                    String pass=rs.getString("password");
                    
                    if(jTusername.getText().equals("Username") || jPasswordF.getText().equals("Password")){
                        jLabel2.setText("Please enter Username or Password");
                    }else if(uname.equals("admin")){
                         if(pass2.equals("admin") ){
                            
                             u.setVisible(true);
                             this.setVisible(false);
                         }
                    }
                    else{
                        if(uname.equals(unamet)){
                            if(pass2.equals(pass) ){
                                u.setv();
                                u.setVisible(true);
                                this.setVisible(false);
                            }
                            else{
                                jLabel2.setText("Wrong Username or Password");
                            }
                        }  
                    } 
                }
                
                conn.setAutoCommit(false);
                conn.commit();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteProdA.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLexitpnl;
    private javax.swing.JLabel jLiconpass;
    private javax.swing.JLabel jLiconuser;
    private javax.swing.JPasswordField jPasswordF;
    private javax.swing.JPanel jPleftpnl;
    private javax.swing.JPanel jPloginpnl;
    private javax.swing.JPanel jPmainpnl;
    private javax.swing.JPanel jProghtpnl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTusername;
    // End of variables declaration//GEN-END:variables
}
