/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;


/**
 *
 * @author ameer
 */
public class PrintBill extends javax.swing.JFrame {

    /**
     * Creates new form PrintBill
     */
    public PrintBill() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBdeletecolmn = new javax.swing.JButton();
        jLheader = new javax.swing.JLabel();
        jLorderid = new javax.swing.JLabel();
        jTorderid = new javax.swing.JTextField();
        jLcustomname = new javax.swing.JLabel();
        jTcustmname = new javax.swing.JTextField();
        jLpayd = new javax.swing.JLabel();
        jLprice = new javax.swing.JLabel();
        jTprice = new javax.swing.JTextField();
        jLDisc = new javax.swing.JLabel();
        jTdisc = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLmasg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(394, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(396, 507));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 400));

        jBdeletecolmn.setBackground(new java.awt.Color(241, 223, 169));
        jBdeletecolmn.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jBdeletecolmn.setForeground(new java.awt.Color(51, 51, 51));
        jBdeletecolmn.setText("Take the order");
        jBdeletecolmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBdeletecolmnMousePressed(evt);
            }
        });
        jBdeletecolmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletecolmnActionPerformed(evt);
            }
        });

        jLheader.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLheader.setText("Print Bill");

        jLorderid.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLorderid.setText("Order ID :");

        jTorderid.setEditable(false);
        jTorderid.setBackground(new java.awt.Color(45, 72, 77));
        jTorderid.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTorderid.setForeground(new java.awt.Color(255, 255, 255));
        jTorderid.setText(" ");
        jTorderid.setBorder(null);
        jTorderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTorderidActionPerformed(evt);
            }
        });

        jLcustomname.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLcustomname.setText("Customer name :");

        jTcustmname.setBackground(new java.awt.Color(45, 72, 77));
        jTcustmname.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTcustmname.setForeground(new java.awt.Color(255, 255, 255));
        jTcustmname.setText(" ");
        jTcustmname.setBorder(null);
        jTcustmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcustmnameActionPerformed(evt);
            }
        });

        jLpayd.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLpayd.setText("Payment Date :");

        jLprice.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLprice.setText("Price :");

        jTprice.setEditable(false);
        jTprice.setBackground(new java.awt.Color(45, 72, 77));
        jTprice.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTprice.setForeground(new java.awt.Color(255, 255, 255));
        jTprice.setText(" ");
        jTprice.setBorder(null);
        jTprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpriceActionPerformed(evt);
            }
        });

        jLDisc.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLDisc.setText("Discount :");

        jTdisc.setBackground(new java.awt.Color(45, 72, 77));
        jTdisc.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTdisc.setForeground(new java.awt.Color(255, 255, 255));
        jTdisc.setText(" ");
        jTdisc.setBorder(null);
        jTdisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdiscActionPerformed(evt);
            }
        });

        jLmasg.setBackground(new java.awt.Color(241, 223, 169));
        jLmasg.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLmasg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLpayd)
                        .addGap(39, 39, 39)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLorderid)
                                        .addGap(78, 78, 78)
                                        .addComponent(jTorderid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLcustomname)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTcustmname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLprice)
                                        .addGap(110, 110, 110)
                                        .addComponent(jTprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLDisc)
                                        .addGap(78, 78, 78)
                                        .addComponent(jTdisc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLheader))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLmasg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBdeletecolmn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLheader)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLorderid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTorderid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcustmname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcustomname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLpayd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdisc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLmasg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBdeletecolmn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 396, 507));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBdeletecolmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletecolmnActionPerformed
        // TODO add your handling code here:
        try{
            OracleDataSource ods =new OracleDataSource() ;
            ods.setUser("c##ameer");
            ods.setPassword("123456");
            ods.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            Connection conn=ods.getConnection();
            InputStream input = new FileInputStream (new File("Blank_A4.jrxml"));
            JasperDesign jd= JRXmlLoader.load(input);
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp =JasperFillManager.fillReport(jr,null,conn);

            JFrame jf=new JFrame("Report");
            jf.getContentPane().add(new JRViewer(jp));
            jf.pack();
            jf.setVisible(true);
        }catch(Exception ex){
             Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBdeletecolmnActionPerformed

    private void jTorderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTorderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTorderidActionPerformed

    private void jTcustmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcustmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcustmnameActionPerformed

    private void jTpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpriceActionPerformed

    private void jTdiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdiscActionPerformed

    private void jBdeletecolmnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdeletecolmnMousePressed
        // TODO add your handling code here
        try {
            // TODO add your handling code here:
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");  
            
                String strStmt="insert into orderinfo (ORDER_ID, CUSTOMER_NAME, QUANTITY,DATE_OF_PURCHASE,PRICE,DISCOUNT) values (?,?,?,to_date(?, 'dd-MM-yyyy'),?,?)";     
                PreparedStatement pst= conn.prepareStatement(strStmt); 
                        if(jTcustmname.getText().trim().isEmpty()){
                        jLmasg.setText("Please enter the empty field");
                        }
                        else{
                        pst.setInt(1, Integer.parseInt(jTorderid.getText().trim()));
            
                        pst.setString(2, jTcustmname.getText());
            
                        pst.setInt(3,sumqu);
            
                        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                        String date= sdf.format(jDateChooser1.getDate());
                        pst.setString(4, date);
            
                        pst.setInt(5,Integer.parseInt(jTprice.getText().trim()));
                        pst.setInt(6,Integer.parseInt(jTdisc.getText().trim()));
                        pst.executeUpdate();
                        }
                        conn.setAutoCommit(false);
                        conn.commit();
                        conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jBdeletecolmnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintBill().setVisible(true);
            }
        });
    }
    
    void addtojtxtf(JTable T){
    int sumq=0,sumprice=0,ID=0;
    Date d=new Date();
    prictot=0;
    for(int i=0 ; i< T.getRowCount() ; i++){
        sumq =sumq + Integer.parseInt(T.getValueAt(i, 2).toString());
        sumprice = sumprice + Integer.parseInt(T.getValueAt(i, 3).toString());
        prictot = prictot + Integer.parseInt(T.getValueAt(i, 2).toString()) * Integer.parseInt(T.getValueAt(i, 3).toString());
    }
    
   // jTqu.setText(String.valueOf(sumq));
    sumqu=sumq;
   
    jTprice.setText(String.valueOf(prictot));
    jDateChooser1.setDate(d);
    jTdisc.setText("0");
  
    
    String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from orderinfo";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
             ID =rs.getInt("order_id");
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    orderId=ID + 1;
    jTorderid.setText(String.valueOf(orderId));
    }
    
    int orderId,sumqu,prictot;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdeletecolmn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLDisc;
    private javax.swing.JLabel jLcustomname;
    private javax.swing.JLabel jLheader;
    private javax.swing.JLabel jLmasg;
    private javax.swing.JLabel jLorderid;
    private javax.swing.JLabel jLpayd;
    private javax.swing.JLabel jLprice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTcustmname;
    private javax.swing.JTextField jTdisc;
    private javax.swing.JTextField jTorderid;
    private javax.swing.JTextField jTprice;
    // End of variables declaration//GEN-END:variables
}
