/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbgtcar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ameer
 */
public class SearchProd extends javax.swing.JFrame {

    /**
     * Creates new form SearchProd
     */
   
    
        
    
        public SearchProd() {
        initComponents();
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTsearchbyname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaddprod = new javax.swing.JTable();

        setBackground(new java.awt.Color(241, 223, 169));

        jPanel1.setBackground(new java.awt.Color(241, 223, 169));

        jTsearchbyname.setBackground(new java.awt.Color(241, 223, 169));
        jTsearchbyname.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jTsearchbyname.setText("SEARCH BY NAME PRODUCT");
        jTsearchbyname.setBorder(null);
        jTsearchbyname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTsearchbynameMousePressed(evt);
            }
        });
        jTsearchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchbynameActionPerformed(evt);
            }
        });
        jTsearchbyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTsearchbynameKeyReleased(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane2.setBorder(null);

        jTaddprod.setAutoCreateRowSorter(true);
        jTaddprod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTaddprod.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTaddprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial ID", "Product Name", "Quantity", "Date Of Purchase", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTaddprod.setGridColor(new java.awt.Color(255, 255, 255));
        jTaddprod.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaddprodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTaddprod);
        if (jTaddprod.getColumnModel().getColumnCount() > 0) {
            jTaddprod.getColumnModel().getColumn(0).setResizable(false);
            jTaddprod.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTaddprod.getColumnModel().getColumn(1).setResizable(false);
            jTaddprod.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTaddprod.getColumnModel().getColumn(2).setResizable(false);
            jTaddprod.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTaddprod.getColumnModel().getColumn(3).setResizable(false);
            jTaddprod.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTaddprod.getColumnModel().getColumn(4).setResizable(false);
            jTaddprod.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jTsearchbyname))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTsearchbynameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTsearchbynameMousePressed
        // TODO add your handling code here:
        jTsearchbyname.setText("");
    }//GEN-LAST:event_jTsearchbynameMousePressed

    private void jTsearchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchbynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsearchbynameActionPerformed

    private void jTaddprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaddprodMouseClicked
        // TODO add your handling code here:
        TableModel m=jTaddprod.getModel();
        int index =jTaddprod.getSelectedRow();
        
        int id =Integer.parseInt(m.getValueAt(index, 0).toString());
        String pdn =m.getValueAt(index, 1).toString();
        int q=Integer.parseInt(m.getValueAt(index, 2).toString());
        int price=Integer.parseInt(m.getValueAt(index, 4).toString());
        if(AdminInterface.existsInTable(id)){
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f,"The product already exist");
        }
        else{
            q=0;
        AdminInterface.addtotablesell(new Object[]{
                                        id,
                                        pdn,
                                        q,
                                        price,
              });
        }
        
    }//GEN-LAST:event_jTaddprodMouseClicked

    private void jTsearchbynameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTsearchbynameKeyReleased
        // TODO add your handling code here:
         DefaultTableModel table= (DefaultTableModel)jTaddprod.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        jTaddprod.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTsearchbyname.getText(),1));
    }//GEN-LAST:event_jTsearchbynameKeyReleased

    /**
     * @param args the command line arguments
     */
    void displayprod(String carT , String carN){
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        ResultSet rs,rs2,rs3;
        
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            
         
            
            String sql="select prod_id from prodcar where car_id = ?";
            String sql2="select * from product";
            String sql3="select car_id from car where car_type = ? and car_name = ? ";
            
            PreparedStatement pst= conn.prepareStatement(sql);
            PreparedStatement pst2= conn.prepareStatement(sql2);
            PreparedStatement pst3= conn.prepareStatement(sql3);
            
           
            rs2=pst2.executeQuery();
           
            
            DefaultTableModel tblmodel=(DefaultTableModel) jTaddprod.getModel();
            tblmodel.setRowCount(0);
            
            pst3.setString(1, carT);
            pst3.setString(2, carN);
            rs3=pst3.executeQuery();
            if(rs3.next()){
                int carid= rs3.getInt("car_id");
                //String cart = rs.getString("car_type");
                //String carn = rs.getString("car_name");
                pst.setInt(1, carid);
                rs=pst.executeQuery();
                if(rs.next()){
                    int prodid=rs.getInt("prod_id");
                   
                    while(rs2.next()){
                        int ID = rs2.getInt("prod_id");
                        String name=rs2.getString("prod_name");
                        String Q = String.valueOf(rs2.getInt("Quantity"));
                        String DateofP= rs2.getString("Date_of_Purchase");
                        String Price=String.valueOf(rs2.getInt("price"));

                        if( prodid == ID){
                            String tbData[]={String.valueOf(ID),name,Q,DateofP,Price};
                            tblmodel.addRow(tbData);
                        }
                    }
                }
            }         
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    void displayallprod(){
    String url="jdbc:oracle:thin:@localhost:1521:xe";
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn=DriverManager.getConnection(url, "c##ameer", "123456");
            Statement st = conn.createStatement();
            String sql="select * from product";
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel tblmodel=(DefaultTableModel) jTaddprod.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
            String ID = String.valueOf(rs.getInt("prod_id"));
            String name=rs.getString("prod_name");
            String Q = String.valueOf(rs.getInt("Quantity"));
            String DateofP= rs.getString("Date_of_Purchase");
            String Price=String.valueOf(rs.getInt("price"));
            
            String tbData[]={ID,name,Q,DateofP,Price};
            tblmodel.addRow(tbData);
            
            }
            conn.setAutoCommit(false);
            conn.commit();
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new SearchProd().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTaddprod;
    private javax.swing.JTextField jTsearchbyname;
    // End of variables declaration//GEN-END:variables
}
